- hosts: gitlab 
  gather_facts: true
  become:
    true
  become_method:
    sudo
  become_user:
    root
  remote_user:
    ubuntu
  roles:
   - update
   - gitlab

  environment:
     http_proxy: http://lodyanyy.ru:8118
     https_proxy: http://lodyanyy.ru:8118
  
